extends Node

# E => Nothing
# X => Chaos Block
# P => Player
# S => Solid not movable
# F => finish door where the player should go
# K => KEY the player have to pick up this key to be able to open the door the F
# I => ice

var map = null

var editor_selected_block = "X"

var created_map = [
	"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
]

var map1 = [
	"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEKEES",
	"SEEEEEEEEPEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSS",
	"SSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEESEEEEES",
	"SEEEEEEEEEESEEEEEEEEEEEEEEEEEEEEEEEEEESEEEEES",
	"SEEEEEEEEEESXEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEFS",
	"SEEEEEEEEEESEXEEEEEEEEEEEEEEEEEEEEEEEESSSSSSS",
	"SEEEEEEEEEESXEEEEEEEEEEEEEEEEEEEEEEEEESEEEEES",
	"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
]

var map2 = [
	"SSSSSSSSSSSSSSSSSS",
	"SEEEEEEEEXEXEEEEES",
	"SEEEEEEEEEXEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SPEEEEEEEEEEEEEEES",
	"SIIIIIIIIIIIIIIIIS",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEES",
	"SEEEEEEEFEEEEEEEES",
	"SSSSSSSSSSSSSSSSSS",
]

var map3 = [
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		"SEEXEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
		"SEXXEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
		"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
		"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
		"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
		"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
		"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
		"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
		"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
		"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
		"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
		"SEEEEEEEEEEEEEEEEEPEEEEEEEEEEEEES",
		"SSSSSSSSSSSSSIIISSSSSSSSSSSSSSSSS",
		"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
		"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
		"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
		"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
		"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEES",
		"SEEEEEEEEEEEEEEEEEEEEEEEEEEEEEXFS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
]

var map4 = [
	"SSSSSSSSSS",
	"SEEEEEEIES",
	"SEEEEEEIES",
	"SEEEEEEIES",
	"SEEEEEEIES",
	"SPEEEEEIFS",
	"SSSSSSSSSS",
]

var map5 = [
	"SSSSSSSSSSSSSSSSSSSS",
	"SEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEXEEEEEEEES",
	"SEPEEKKKKKKKKKKKEFES",
	"SSSSSEEEEEEEEEEESSSS",
	"SEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEES",
	"SSSSSSSSSSSSSSSSSSSS",
]

var map6 = [
	"SSSSSSSSSS",
	"SEEEEEEEES",
	"SEEEEEEEKS",
	"SSSEEESSSS",
	"SEEEEEEEES",
	"SEEEEEEEES",
	"SEEEEEEEES",
	"SEEEEEEEES",
	"SEPEEEEEFS",
	"SSSXXXSSSS",
	"SEEEEEEEES",
	"SEEEEEEEES",
	"SEEEEEEEES",
	"SEEEEEEEES",
	"SEEEEEEEES",
	"SEEEEEEEES",
	"SEEEEEEEES",
	"SEEEEEEEES",
	"SEEEEEEEKS",
	"SSSEEESSSS",
	"SSSSSSSSSS",
]

var map7 = [
	"SSSSSSSSSSSSSSSSSSSSSS",
	"SEEEEEEEEEEEEEEEEEEEES",
	"SEXEEEEEEEEEEEEEEEEEES",
	"SEPEEEEEEEEEEEEEEEEEFS",
	"SSSSSSSSEEEEESSSSSSSSS",
	"SSSSSSSSSSSSSSSSSSSSSS",
]

var map8 = [
	"SSSSSSSSSSSSSSSSSSSSSS",
	"SEXEEEEEEESEEEESEEEEES",
	"SXXEEEEEEESEEEESEEEEES",
	"SEEEEEEEEESEEEESEEEEES",
	"SEEEEEEEEESPEEEEEEEEFS",
	"SEEEEEEEEESSSEEESSSSSS",
	"SEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEES",
	"SSSSSSSSSSSSSSSSSSSSSS",
]

var map9 = [
	"SSSSSSSSSSSSSSSSSSSSSS",
	"SEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEKS",
	"SEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEEEEEEES",
	"SEEEEEEEEEEEEEEESEXEES",
	"SEEEEEEEEEEEEEEESEEEES",
	"SEXEEEEEEEEEEEEESSSSSS",
	"SEPEEEEEEEEEEEEEEEEEFS",
	"SSSSSSSSSSSSSSSSSSSSSS",
]

var current_map = null
var maps = [map1,map2,map3,map4,map5,map6,map7,map8,map9,created_map]
var key_count = 0

var keys = 0

var is_create_menu_visible = false

var from = [
	[
		"EEE",
		"EEE",
		"EEE"
	],
	[
		"EEE",
		"EEE",
		"EEE"
	],
	[
		"EEE",
		"EEE",
		"EEE"
	],
]

var to = [
	[
		"EEE",
		"EEE",
		"EEE"
	],
	[
		"EEE",
		"EEE",
		"EEE"
	],
	[
		"EEE",
		"EEE",
		"EEE"
	],
]

var menu = false
var start = false


var is_chaos_selected = true

var speed = 0.2

var ab = null
var cd = null

var editor_cursor = null

func reset_rules():
	to = [
	[
		"EEE",
		"EEE",
		"EEE"
	],
	[
		"EEE",
		"EEE",
		"EEE"
	],
	[
		"EEE",
		"EEE",
		"EEE"
	],
]

	from = [
	[
		"EEE",
		"EEE",
		"EEE"
	],
	[
		"EEE",
		"EEE",
		"EEE"
	],
	[
		"EEE",
		"EEE",
		"EEE"
	],
	
]

	start = false
	is_chaos_selected = true

var editor_motions = true
	
